# clock
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

# seven segment + anodes
set_property PACKAGE_PIN W7 [get_ports {sev_seg_out[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_out[0]}]
set_property PACKAGE_PIN W6 [get_ports {sev_seg_out[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_out[1]}]
set_property PACKAGE_PIN U8 [get_ports {sev_seg_out[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_out[2]}]
set_property PACKAGE_PIN V8 [get_ports {sev_seg_out[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {sev_seg_out[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_out[4]}]
set_property PACKAGE_PIN V5 [get_ports {sev_seg_out[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_out[5]}]
set_property PACKAGE_PIN U7 [get_ports {sev_seg_out[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_out[6]}]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
        set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
 
# buttons       
set_property PACKAGE_PIN U18 [get_ports {btn[0]}]						
    set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]
set_property PACKAGE_PIN T18 [get_ports {btn[1]}]                        
    set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
set_property PACKAGE_PIN U17 [get_ports {btn[2]}]                        
    set_property IOSTANDARD LVCMOS33 [get_ports {btn[2]}]